name: Create Archive
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Archive Checker
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "checker.zip"
          exclusions: "*.git* /*service/* README.md LICENSE"

      - name: Archive Service
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "service.zip"
          exclusions: "*.git* /*checker/* README.md LICENSE"

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: |
            "release.zip"
            "service.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
